version: "3.8"

services:
  lambda:
    image: golang:alpine3.16
    volumes:
      - ./lambda:/go/src
  terraform:
    image: hashicorp/terraform:1.3.3
    volumes:
      - .:/usr/src
    env_file: .env
    entrypoint: ""
    working_dir: /usr/src/terraform
